// @ts-nocheck -- skip type checking
import * as docs_8 from "../content/docs/python/troubleshooting.mdx?collection=docs&hash=1747007664859"
import * as docs_7 from "../content/docs/python/installation.mdx?collection=docs&hash=1747007664859"
import * as docs_6 from "../content/docs/python/file-formats.mdx?collection=docs&hash=1747007664859"
import * as docs_5 from "../content/docs/python/examples.mdx?collection=docs&hash=1747007664859"
import * as docs_4 from "../content/docs/python/authentication.mdx?collection=docs&hash=1747007664859"
import * as docs_3 from "../content/docs/python/api-reference.mdx?collection=docs&hash=1747007664859"
import * as docs_2 from "../content/docs/quickstart.mdx?collection=docs&hash=1747007664859"
import * as docs_1 from "../content/docs/index.mdx?collection=docs&hash=1747007664859"
import * as docs_0 from "../content/docs/file-formats.mdx?collection=docs&hash=1747007664859"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"file-formats.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/file-formats.mdx"}, data: docs_0 }, { info: {"path":"index.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/index.mdx"}, data: docs_1 }, { info: {"path":"quickstart.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/quickstart.mdx"}, data: docs_2 }, { info: {"path":"python/api-reference.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/python/api-reference.mdx"}, data: docs_3 }, { info: {"path":"python/authentication.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/python/authentication.mdx"}, data: docs_4 }, { info: {"path":"python/examples.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/python/examples.mdx"}, data: docs_5 }, { info: {"path":"python/file-formats.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/python/file-formats.mdx"}, data: docs_6 }, { info: {"path":"python/installation.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/python/installation.mdx"}, data: docs_7 }, { info: {"path":"python/troubleshooting.mdx","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/python/troubleshooting.mdx"}, data: docs_8 }], [{"info":{"path":"meta.json","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/meta.json"},"data":{"title":"RunRL Documentation","pages":["index","quickstart","file-formats","python"]}}, {"info":{"path":"python/meta.json","absolutePath":"/Users/dyusha/runrl/docs/rldocs/content/docs/python/meta.json"},"data":{"title":"Python SDK","pages":["installation","authentication","api-reference","examples","file-formats","troubleshooting"]}}])